// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZRJu7NjbmdTfnRgqWo1VdrF_qaPRt2mo',
    appId: '1:308782549397:web:482c11281fcdfdefc9ce9c',
    messagingSenderId: '308782549397',
    projectId: 'londree-75feb',
    authDomain: 'londree-75feb.firebaseapp.com',
    storageBucket: 'londree-75feb.appspot.com',
    measurementId: 'G-559RKVW497',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQvmic-fWjfF9KjXJ4sQwr_nqY_mIr5Hk',
    appId: '1:308782549397:android:c63fa2aa03357139c9ce9c',
    messagingSenderId: '308782549397',
    projectId: 'londree-75feb',
    storageBucket: 'londree-75feb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh7Omxr4VP0CCl_38eyDQH_aVgb5kHf4Q',
    appId: '1:308782549397:ios:4702272704ae9c68c9ce9c',
    messagingSenderId: '308782549397',
    projectId: 'londree-75feb',
    storageBucket: 'londree-75feb.appspot.com',
    iosClientId: '308782549397-5u7t5mpd1gf9v300ars7ohojujku60bs.apps.googleusercontent.com',
    iosBundleId: 'com.example.londreeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh7Omxr4VP0CCl_38eyDQH_aVgb5kHf4Q',
    appId: '1:308782549397:ios:4702272704ae9c68c9ce9c',
    messagingSenderId: '308782549397',
    projectId: 'londree-75feb',
    storageBucket: 'londree-75feb.appspot.com',
    iosClientId: '308782549397-5u7t5mpd1gf9v300ars7ohojujku60bs.apps.googleusercontent.com',
    iosBundleId: 'com.example.londreeapp',
  );
}
